server:
    port: 11005

spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://39.107.80.231:3306/SSO?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
        username: HengTian
        password: HengTian0.0

    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true